export const SEARCH_MOVE_START = "SEARCH_MOVE_START";
export const SEARCH_MOVE_ERROR = "SEARCH_MOVE_ERROR";
export const SEARCH_MOVE_COMPLETE = "SEARCH_MOVE_COMPLETE";

export const SEARCH_MOVIE_BY_ID_START = "SEARCH_MOVIE_BY_ID_START";
export const SEARCH_MOVIE_BY_ID_ERROR = "SEARCH_MOVIE_BY_ID_ERROR";
export const SEARCH_MOVIE_BY_ID_COMPLETE = "SEARCH_MOVIE_BY_ID_COMPLETE";

